# Metadata
title: Dmitry Semenov
tagline: Software Developer
description: Personal Website
url: https://lonelyteapot.github.io
username: lonelyteapot
social:
  links:
    - https://github.com/lonelyteapot
    - https://t.me/lonelyteapot

# Jekyll
permalink: /:slug
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - package.json
defaults:
  - scope:
      path: ""
    values:
      image: /images/screenshot.webp

# Custom variables
main_header_title: Dmitry Semenov
main_header_bio: Software Developer
main_header_nickname: "@lonelyteapot"
copyright_name: Dmitry Semenov
copyright_year: 2022
analytics:
  google:
    id: G-4N4MCBCG3C

# Sass Converter plugin
sass:
  implementation: sass-embedded
  style: expanded
  sass_dir: _sass
  line_comments: false
  sourcemap: always
