permalink: /:categories/:year/:month/:day/:title:output_ext

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

sass:
  implementation: sass-embedded
  style: expanded
  sass_dir: _sass
  line_comments: false
  sourcemap: always
